Task1.1 solution
Vomchick/.Net-Homework pull request #1
Opened 2024-04-22 07:21 UTC by Vomchick

2024-04-23 11:47 UTC, IgorKheidorov requested changes
Good solution, just fix issue

2024-04-23 11:47 UTC, IgorKheidorov commented on Task1.1/Program.cs
> +        static void Main(string[] args)
b can be less then a, order is not defined in a task. Values can be negative

2024-04-24 06:04 UTC, Vomchick commented on Task1.1/Program.cs
> +                }
Can if statement be used without {}, just with one enter? Because using brackets will use 2 more rows 😊

2024-04-24 06:23 UTC, Vomchick commented on Task1.1/Program.cs
> +                }
Heh, you answered the question on the lecture, even when you didn't know about it. Thanks

2024-04-24 11:11 UTC, IgorKheidorov approved these changes

2024-04-24 15:55 UTC, merged