Task1.3 solution
Vomchick/.Net-Homework pull request #3
Opened 2024-04-22 07:22 UTC by Vomchick

2024-04-23 12:11 UTC, IgorKheidorov requested changes
See comments

2024-04-23 12:11 UTC, IgorKheidorov commented on Task1.3/Program.cs
> +
Code style

2024-04-23 12:11 UTC, IgorKheidorov commented on Task1.3/Program.cs
> +            var set = SetCreation(arr);
Code style, body of the loop in brackets

2024-04-23 12:11 UTC, IgorKheidorov commented on Task1.3/Program.cs
> +            int count = 0;
No need to iterate via array twice, first loop is just to calculate the size of final array (set). Better to copy unique values to a temp array with the same size as original, calculate actual length in the same loop as copy operation, and than use the truncated array as resulting

2024-04-23 12:11 UTC, IgorKheidorov commented on Task1.3/Program.cs
> +                }
code style

2024-04-23 17:01 UTC, Vomchick commented on Task1.3/Program.cs
> +
What do you mean by a code style in this case?

2024-04-24 11:13 UTC, IgorKheidorov approved these changes

2024-04-25 19:36 UTC, merged